# Generated by Django 4.2.8 on 2025-12-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='訂單編號', max_length=100, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='總價', max_digits=10)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
            ],
            options={
                'db_table': 'api_order',
                'ordering': ['-created_time'],
            },
        ),
    ]
