# Generated by Django 4.2.8 on 2025-12-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_time',
            field=models.DateTimeField(blank=True, help_text='刪除時間 (軟刪除)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, help_text='最後更新時間'),
        ),
    ]
