# Generated by Django 4.2.8 on 2025-12-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_deleted_time_order_updated_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['deleted_time'], name='api_order_deleted_177d59_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_time'], name='api_order_created_d44e46_idx'),
        ),
    ]
